### ISSUE TITLE
request: setting 1/3 phase and max current

### ISSUE THREAD

**Issue by Dominic-070** [sockless-coding/garo_wallbox#32]
Is there a possibility that there will be a function that allows you to switch between 1 and 3 phase from the integration
and can set the max current (with a slider)?

**Comment by sockless-coding** [comment]
Hi @Dominic-070,

As far as I know, you can't change the number of allowed phases from the configuration.
But you can change the current limit by calling:
```yaml
service: garo_wallbox.set_current_limit
data:
   entity_id: sensor.garage_charger
   limit: 16
```
