### ISSUE TITLE
garo home assistant switch off and on

### ISSUE THREAD

**Issue by bjarne007** [sockless-coding/garo_wallbox#33]
Hi
is it posible to switch on and off a GARO Wallbox with Home Assistant
if yes how ?

**Comment by stejo388** [comment]
Hi, I have the same problem. The garo_wallbox.set_mode seems not work

**Comment by sockless-coding** [comment]
Hi,
Calling `garo_wallbox.set_mode` should set the mode of the wallbox.
Ex. 
Enable charging
```yaml
service: garo_wallbox.set_mode
data:
  entity_id: sensor.garage_charger
  mode: "On"
```

Disable charging
```yaml
service: garo_wallbox.set_mode
data:
  entity_id: sensor.garage_charger
  mode: "Off"
```
